### ISSUE TITLE
.dcignore not working

### ISSUE THREAD

**Issue by Ayfri** [DeepCodeAI/jetbrains-plugin#10]
Hi, I have a `.dcignore` with this into it : `node_modules/**`.
But DeepCode still scan the directory `node_modules` and all the files in it, what I am doing wrong ?

**Comment by ArtsiomCh** [comment]
Hi Ayfri. Yes indeed we had some trouble with parsing `/**` part. Will be fixed in next release. For now try to use just `node_modules/` (or even simpler `node_modules`).
Thank you for reporting!
