### ISSUE TITLE
Dropdown menu graphical issue

### ISSUE THREAD

**Issue by douglascdev** [DeepCodeAI/jetbrains-plugin#14]
The plugin is working as intended, but there is a graphical issue on the Dropdown menu item for Deepcode, at **View > Tool windows > Deepcode**. Here's a screenshot of it:
![Screenshot from 2020-09-08 15-33-33](https://user-images.githubusercontent.com/38195951/92515238-b08e2100-f1e9-11ea-8ee3-3c6a038dae90.png)
:
I tried multiple themes and fonts and removing the UI plugin I had installed to see if that was the source of this issue, but that did not work. I'm running Ubuntu 20.04 along with Pycharm 2020.2.1 and DeepCode 1.2.8, here's my log file:

[idea.log](https://github.com/DeepCodeAI/jetbrains-plugin/files/5190387/idea.log)

**Comment by ArtsiomCh** [comment]
Fixed with recent releases (summary icon moved to separate status bar).
