### ISSUE TITLE
Plugin not working in PyCharm 2021.1

### ISSUE THREAD

**Issue by lighthill** [DeepCodeAI/jetbrains-plugin#18]
Error message on IDE startup is:
_Plugin error: Plugin 'DeepCode' (version '1.2.12') is not compatible with the current version of the IDE, because it requires build 204 or older but the current build is PY-211.6693.115_

I think the file "build.gradle", line 33 needs to be changed but I'm not sure what to?
`patchPluginXml {
    sinceBuild 192
    untilBuild 204 
}`

**Comment by ArtsiomCh** [comment]
Dear developers, thank you for your support and feedback!
With the DeepCode acquisition by [Snyk](https://snyk.io) we will be starting a new journey, a better one, towards helping you write robust and secure application code. The DeepCode plugin will be replaced by [Snyk's JetBrains plugin](https://plugins.jetbrains.com/plugin/10972-snyk-vulnerability-scanner) with includes DeepCode's functionality and more.
If you want to read more about it, here is the [official announcement](https://www.deepcode.ai/). We will start sunsetting the official DeepCode API in August, 2021. In the mean time we will do one last update of the JetBrains plugin with this message to ensure you are up to date.
We invite you to join us and start using the new Snyk plugin! We are excited and looking forward to helping you build stable and secure applications 🚀
