### ISSUE TITLE
Some sources for building the plugin are missing!

### ISSUE THREAD

**Issue by vyach-vasiliev** [DeepCodeAI/jetbrains-plugin#19]
There is no `ai.deepcode.javaclient` package with sources for the `DeepCodeExternalAnnotator.java` file. 
Because of this, it is impossible to build the plugin yourself.

Please add the missing files so that people can upgrade the compatibility with the new IDE release for you.

branch: `master`

**Comment by ArtsiomCh** [comment]
To build it locally please see DeveloperGuide.md

**Comment by ArtsiomCh** [comment]
Dear developers, thank you for your support and feedback!
With the DeepCode acquisition by [Snyk](https://snyk.io) we will be starting a new journey, a better one, towards helping you write robust and secure application code. The DeepCode plugin will be replaced by [Snyk's JetBrains plugin](https://plugins.jetbrains.com/plugin/10972-snyk-vulnerability-scanner) with includes DeepCode's functionality and more.
If you want to read more about it, here is the [official announcement](https://www.deepcode.ai/). We will start sunsetting the official DeepCode API in August, 2021. In the mean time we will do one last update of the JetBrains plugin with this message to ensure you are up to date.
We invite you to join us and start using the new Snyk plugin! We are excited and looking forward to helping you build stable and secure applications 🚀
