### ISSUE TITLE
Analysis still runs during the build which crashed CLion.

### ISSUE THREAD

**Issue by Arvi3d** [DeepCodeAI/jetbrains-plugin#2]
Created based on this user feedback: https://plugins.jetbrains.com/plugin/14350-deepcode/reviews#review=41349

**Comment by ArtsiomCh** [comment]
Seems to be fixed at #3 1.0.1
If happens again please create new issue with idea.log ([Locating IDE log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)) attached

**Comment by Michoumichmich** [comment]
Yes it works fine now :) Sorry I couldn't attach the log given the fact I posted a review. I'll try to update it btw
