### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tukali** [DeepCodeAI/jetbrains-plugin#8]
always show:
DeepCode: Error connecting to the server. Check your Settings, Network connection and/or try again later.
so i'can't login,can't use it ,but my network connection is good

**Comment by ArtsiomCh** [comment]
Hi! Please check if internet is really present and settings -> deepcode server has correct value.
If issue still present give us idea.log file attached: https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by Arvi3d** [comment]
Dear @Tukali I confirm, that we have server issues. Now your it should be fine. Please try again. I'm sorry for this inconvinience.
